### ISSUE TITLE
独立页面样式错误

### ISSUE THREAD

**Issue by yanzhonghui** [AirboZH/halo-theme-chirpy#100]
在浅色主题下，用户登录后，访问独立页面时，下方评论区，用户名称无法看清，显示的效果需优化。

Chirpy 版本 1.1.0
Chirpy Add-on 版本 0.0.2

**Comment by AirboZH** [comment]
#94

**Comment by AirboZH** [comment]
关注一下上面提到的Issue吧，这个问题是主题和评论插件颜色适配的问题，最近有很多人说，我优先处理一下~

**Comment by AirboZH** [comment]
抱歉，最近有些忙，这个问题已经解决~  详见：https://github.com/AirboZH/halo-theme-chirpy/pull/105
目前 1.2.0 版本尚未发布
您可以通过 https://github.com/AirboZH/halo-theme-chirpy/actions/runs/6490103594 下方的Artifacts下载更新使用
