### ISSUE TITLE
多语言适配

### ISSUE THREAD

**Issue by liuxin03014** [AirboZH/halo-theme-chirpy#112]

**Comment by AirboZH** [comment]
目前这个阶段还没有全英语的版本，不过有计划开发多语言的版本。可能还需要一段时间。

**Comment by liuxin03014** [comment]
> 目前这个阶段还没有全英文的版本，不过有计划开发多语言的版本。可能还需要一段时间。
那就太棒了，到时候我就把博客从wordpress迁移到halo上来！

**Comment by AirboZH** [comment]
可以初步看看效果，有翻译不准确的地方可以和我反馈

https://airbozh.tech?language=en

如果你系统默认是中文的话，可能需要在url后加`?language=en`
