### ISSUE TITLE
建议适配瞬间和相册

### ISSUE THREAD

**Issue by jkjoy** [AirboZH/halo-theme-chirpy#116]
**RT**

**Comment by AirboZH** [comment]
感谢你的issue，适配瞬间和相册主要有一个难题。
chirpy是一个移植主题，原主题并没用相关的页面，而我也不具备UI相关的知识。设计页面对我们来说是一个挑战
其次，这个主题是一个专注于内容的主题，所以目前这个阶段我可能会花更多时间在内容的展示和一些主题细节的优化上

当然，如果你有好的设计也可以继续和我交流

**Comment by AirboZH** [comment]
后续进度关注 #119

**Comment by AirboZH** [comment]
将会在 #137 适配相册插件
