### ISSUE TITLE
左上角目录和右上角搜索失灵

### ISSUE THREAD

**Issue by vveg26** [AirboZH/halo-theme-chirpy#12]
- [ ] ios端首页点进去一篇文章之后左上角的目录按钮和右上角的搜索按钮失效，无法点击
safari和chrome都如此

- [x] [深色模式下标题字体太黑](https://github.com/AirboZH/halo-theme-chirpy/issues/13)

![pic.jpeg](https://s2.loli.net/2023/08/15/rd4G9jJBtRigcCL.jpg)

**Comment by AirboZH** [comment]
这个问题可能不止存在于 IOS 和移动端

已经初步排查出问题所在，感谢反馈😊

**Comment by AirboZH** [comment]
@all-contributors please add @vveg26 for bug report

**Comment by AirboZH** [comment]
@all-contributors please add @vveg26 for bug report

**Comment by nbgbn** [comment]
移动端左上角的目录按钮好像仍然是失效的，使用的版本是 halo 2.9 +  halo-theme-chirpy 1.1.0，搜索按钮正常。

**Comment by AirboZH** [comment]
> 移动端左上角的目录按钮好像仍然是失效的，使用的版本是 halo 2.9 +  halo-theme-chirpy 1.1.0，搜索按钮正常。

@nbgbn 这个确实之前是解决了不过先最新的版本好像又出现了。

我建议新建一个issue，然后我来排查处理
