### ISSUE TITLE
适配友链页面

### ISSUE THREAD

**Issue by Camellia-2** [AirboZH/halo-theme-chirpy#123]
- 我今天闲着没事按照 RyanWang 的`链接管理插件`配置了下,`400错误`或`500错误`😅
- 我搞不来,还是您出手吧,给增加个友链的模板吧😄

**Comment by AirboZH** [comment]
参考：https://bbs.halo.run/d/4563-links%E9%93%BE%E6%8E%A5%E8%AE%BE%E7%BD%AE%E7%9A%84%E9%97%AE%E9%A2%98/10
