### ISSUE TITLE
【BUG】右上角搜索失灵

### ISSUE THREAD

**Issue by heihei180** [AirboZH/halo-theme-chirpy#128]
您好：
我再使用chirpy的时候，发现 pc端的搜索按钮没有反应。

chipy version：Chirpy
halo version：2.10.2

谢谢~

**Comment by AirboZH** [comment]
是否有安装搜索插件？
方便提供站点么？或者F12 Console是否有报错信息。

**Comment by AirboZH** [comment]
需要安装 https://www.halo.run/store/apps/app-DlacW
