### ISSUE TITLE
希望可以适配表格

### ISSUE THREAD

**Issue by GD2021** [AirboZH/halo-theme-chirpy#129]
## 常规设置

在该设置项里，仅需要设置一下使用 `过滤器和 Hosts 文件拦截指定域名`。该配置项规定了更新过滤器的时间，通常我们认为 24 小时是一个合理的区间，您可以根据自己的需求进行增大或者缩小。

剩下的安全搜索，家长控制，浏览安全，则是没有必要的功能，因为境内使用体验不佳。

关于日志，您需要根据您的存储空间大小来选择一个比较合理的区间，举个例子：

| 通常设备类型 | 通常存储大小 | 建议日志保留时间 |
| --- | --- | --- |
| 小存储设备 | 256 MiB / 512 MiB / etc. | 建议日志不要过大，建议只保留一天 |
| 服务器 | \> 10 Gib | 根据您的存储使用情况，可以七天以上，我个人选择直接保留 90 天 |

被忽略的网域选项：它适用于大量无用查询的情况。举个例子，如果您通过查询日志发现有大量的 `dataflow.biliapi.com` 查询，这些查询是无用的，并且会占用日志空间，那么您可以将其添加到忽略网域列表中，以减少日志空间的浪费。

预览：

![image](https://github.com/AirboZH/halo-theme-chirpy/assets/81171294/81313c0a-9fb8-49e2-b807-31dcfc135bf4)

**Comment by GD2021** [comment]
![image](https://github.com/AirboZH/halo-theme-chirpy/assets/81171294/b10ea971-4b2e-41ff-b526-2b85fd54fa99)
代码ne能否可以实现这种呢？

**Comment by AirboZH** [comment]
第一个表格适配我收到了
![image](https://github.com/AirboZH/halo-theme-chirpy/assets/50261327/3d418a69-e66d-4e0c-b2f9-998523c4bd79)
会照这个样子做

**Comment by AirboZH** [comment]
代码块是这个样子
![image](https://github.com/AirboZH/halo-theme-chirpy/assets/50261327/34f23875-1e9d-48bb-8576-8d99178d99b9)

一直没来及开发，我最近抽空看看。

**Comment by GD2021** [comment]
好的，感谢！！！

**Comment by AirboZH** [comment]
> ![image](https://private-user-images.githubusercontent.com/81171294/288675075-b10ea971-4b2e-41ff-b526-2b85fd54fa99.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg0NTE3MDIsIm5iZiI6MTcwODQ1MTQwMiwicGF0aCI6Ii84MTE3MTI5NC8yODg2NzUwNzUtYjEwZWE5NzEtNGIyZS00MWZmLWI1MjYtMmI4NWZkNTRmYTk5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjIwVDE3NTAwMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRhZjJiYjViN2ExZWYwYTU4MzYyMTliYjNmYjNlYzZhMzk4ZGMzZTFkNzA5YTNlZTRkMjg3YWMxYzYyMTM3M2EmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.P0ibvmki1fO3Mzg-IAHjJhncxIjEj5Q3mb0XKFeYg-Y) 代码ne能否可以实现这种呢？

代码块功能已完成
