### ISSUE TITLE
图片没有居中显示，文字没有两端对齐

### ISSUE THREAD

**Issue by shanyan-wcx** [AirboZH/halo-theme-chirpy#131]
![屏幕截图 2023-12-10 104045](https://github.com/AirboZH/halo-theme-chirpy/assets/58252651/909f96a2-b825-41db-8995-1e8423e31be1)

**Comment by AirboZH** [comment]
可以提供网站链接吗，我目前没有复现这个情况。

您也可以检查一下编辑器，提供一下编辑器信息。

**Comment by shanyan-wcx** [comment]
https://halo.shanyan.online/archives/Unraid%E9%85%8D%E7%BD%AE%EF%BC%88%E4%B8%80%EF%BC%89-%E7%B3%BB%E7%BB%9F%E5%AE%89%E8%A3%85

图片下方的标题似乎也没有正常显示，这是我编辑器里的样子。
![屏幕截图 2023-12-10 110320](https://github.com/AirboZH/halo-theme-chirpy/assets/58252651/060b87ca-84f2-40e5-b8f1-c25e4c8657b1)
