### ISSUE TITLE
文章分享@url获取到的是本地ip

### ISSUE THREAD

**Issue by panming** [AirboZH/halo-theme-chirpy#134]
大佬你好
我使用的1panel自动安装的halo,在主题>文章，设置分享链接时，例如：
https://twitter.com/intent/tweet?&url=@URL
他会解析成
https://twitter.com/intent/tweet?&url=http://localhost:8080/archives/xxxx
我需要修改什么吗？
纯小白，希望能得到你的帮助，万分感谢

**Comment by AirboZH** [comment]
你好，请检查halo设置的外部访问地址是否设置正确
![image](https://github.com/AirboZH/halo-theme-chirpy/assets/50261327/2132ebf6-ff13-4c0b-9830-8b6985ed179d)

**Comment by AirboZH** [comment]
1p可以通过启动参数配置
![image](https://github.com/AirboZH/halo-theme-chirpy/assets/50261327/f917640c-2176-49c1-bc35-52c0a10ec41b)

**Comment by AirboZH** [comment]
> 哦，对了，我在linux平台（debian12），edge浏览器上，侧边栏会有重影，这是浏览器问题吗？如图 

可以提供站点地址我看一下吗？这个之前还没有遇到过。
