### ISSUE TITLE
侧边栏文字重影

### ISSUE THREAD

**Issue by AirboZH** [AirboZH/halo-theme-chirpy#135]
哦，对了，我在linux平台（debian12），edge浏览器上，侧边栏会有重影，这是浏览器问题吗？如图
![QQ20231212-195604](https://github.com/AirboZH/halo-theme-chirpy/assets/8276339/ae556528-6425-4217-afc2-3d24ca39f9b1)

_Originally posted by @panming in https://github.com/AirboZH/halo-theme-chirpy/issues/134#issuecomment-1851931351_

**Comment by AirboZH** [comment]
@panming 可以提供网站地址我看一下么？之前还没遇到过这个情况。你也可以用 `F12` 检查一下 `HTML` 看网点内容是否正常，如果正常可能是CSS或者浏览器的原因。

**Comment by panming** [comment]
linuxcnc.org.cn   我在其他操作系统，其他浏览器都没问题，只在Linux上的edge上遇到了

**Comment by AirboZH** [comment]
你可以尝试看看电脑是否有符合的字体。

https://github.com/AirboZH/halo-theme-chirpy/blob/daa8f0a22fbcb21772782b20832826c5f6a0c9e6/src/css/addon/variables.scss#L31-L32

我使用linux-chrome测试是正常的。

我推测这和电脑系统和安装字体有关系，属于个例，故关闭此issue
