### ISSUE TITLE
关于左侧栏图标

### ISSUE THREAD

**Issue by GD2021** [AirboZH/halo-theme-chirpy#138]
![image](https://github.com/AirboZH/halo-theme-chirpy/assets/81171294/07160bdc-249b-44f7-928c-ac4d8f8301a1)

请问图中的图标如何改变？

**Comment by GD2021** [comment]
为什么我的都相同

**Comment by AirboZH** [comment]
参考wiki
https://github.com/AirboZH/halo-theme-chirpy/wiki/%E4%B8%BB%E9%A2%98%E4%BD%BF%E7%94%A8%E6%96%87%E6%A1%A3#%E5%9B%BE%E6%A0%87
