### ISSUE TITLE
主页新增备案号

### ISSUE THREAD

**Issue by muyiacc** [AirboZH/halo-theme-chirpy#14]
作者你好，这个主题听好看的，请问怎么在主页增加备案号，不太懂这方面

**Comment by AirboZH** [comment]
参考[README #info-自定义信息](https://github.com/AirboZH/halo-theme-chirpy#info-%E8%87%AA%E5%AE%9A%E4%B9%89%E4%BF%A1%E6%81%AF)

> 您可以在Halo Console 设置-代码注入 中编辑页脚

![image](https://github.com/AirboZH/halo-theme-chirpy/assets/50261327/e717e024-4984-4f52-acdd-b3f0436c8d2e)

**Comment by muyiacc** [comment]
感谢指导

**Comment by AirboZH** [comment]
@muyiacc  感谢您支持我的项目，有疑问、建议可以继续提 Issue
