### ISSUE TITLE
开启插件后，代码还是不能高亮显示

### ISSUE THREAD

**Issue by MemoryCollection** [AirboZH/halo-theme-chirpy#142]
![图片](https://github.com/AirboZH/halo-theme-chirpy/assets/27777606/fbbbf0a8-8039-41c1-8821-c5cdb84eae13)
上面是发布后的样子
开启插件后，代码还是不能高亮显示
下面这个是后台编辑时候的样子
![图片](https://github.com/AirboZH/halo-theme-chirpy/assets/27777606/0ba2f900-d718-45d4-82fe-f41eb142d4ea)

**Comment by AirboZH** [comment]
使用的是什么插件呢？方便提供站点地址么

**Comment by MemoryCollection** [comment]
> 使用的是什么插件呢？方便提供站点地址么

![图片](https://github.com/AirboZH/halo-theme-chirpy/assets/27777606/9d37cba3-fe9c-4b19-8618-96694f529229)


wi6.cn

**Comment by MemoryCollection** [comment]
> 使用的是什么插件呢？方便提供站点地址么

秒回呀，辛苦作者了。

**Comment by AirboZH** [comment]
你好，目前主题还没有自定义的代码块，我将在之后完成开发，详细见：#28

你可以安装 halo插件中的代码高亮插件 https://www.halo.run/store/apps/app-sqpgf

**Comment by MemoryCollection** [comment]
> 你好，目前主题还没有自定义的代码块，我将在之后完成开发，详细见：#28
> 
> 你可以安装 halo插件中的代码高亮插件 https://www.halo.run/store/apps/app-sqpgf

好的，辛苦作者了，很优秀的主题

**Comment by AirboZH** [comment]
谢谢你的支持！
