### ISSUE TITLE
[建议] 希望能添加对插件<highlight.js>的支持，以增强在白色/黑色模式切换的良好体验

### ISSUE THREAD

**Issue by Rlxzmdd** [AirboZH/halo-theme-chirpy#144]
【需求】
支持<hightlight.js> 让其能在白色/黑色模式切换。   
在该<hightlight.js>部份样式中（主要集中在白底样式），切换为主题颜色会导致其高亮样式部份失效。目前我通过添加少量css和替换黑色主题解决该问题。

【截图演示】
其中class=hljs为highlight.js注入的类型。
黑色模式：
![image](https://github.com/AirboZH/halo-theme-chirpy/assets/13695917/ab7edd61-bd1e-460b-8872-5fbbe6abc254)
白色模式
![image](https://github.com/AirboZH/halo-theme-chirpy/assets/13695917/8ecebd66-6021-4c57-8ce1-8e8843266ae9)

【网站链接】
https://have.somuch.work/archives/622b0b88-c21f-4777-b491-ef1e97d42613

**Comment by AirboZH** [comment]
抱歉代码块作为基础功能还拖了一些时间，我会尽快处理代码块相关功能。
#28

**Comment by Rlxzmdd** [comment]
https://have.somuch.work/archives/622b0b88-c21f-4777-b491-ef1e97d42613
简单实现了点mac窗口的效果，不过感觉还是挺别扭的。
打算先这样用了，默认为黑色底色。
<style>
  html[data-mode="light"] { 
    --main-bg: #f4f4f4;
    --topbar-bg: #f4f4f4;
  }
  img{
    border-radius: 6px; 
  }
  .hljs {
    border-radius: 6px; /* 调整圆角的大小 */
	background: #282828 !important;
    padding: 1.5em !important;
   }

  html:not([data-mode]) .messageText {
    fill: white !important;
  }
  html:not([data-mode]) .loopText tspan{
    fill: white !important;
  }
  html:not([data-mode]) .messageLine0{
    stroke: white !important;
  }
  
/* 基础样式 */
pre {
    position: relative; /* 为窗口控制按钮定位 */
    border-radius: 10px; /* 圆角 */
    box-shadow: 0 0 20px rgb(0 0 0 / 53%);
    padding-top: 20px; /* 内边距 */
	background: #282828 !important;
}


/* 窗口控制按钮 */
pre::before {
    content: ''; /* 伪元素内容 */
    position: absolute; /* 绝对定位 */
    top: 1em; /* 距顶部位置 */
    left: 1em; /* 距左侧位置 */
    width: 1em; /* 宽度 */
    height: 1em; /* 高度 */
    border-radius: 50%; /* 圆形 */
    background: #434547; /* 红色按钮 */
    box-shadow: 21px 0 0 #434547, 42px 0 0 #434547; /* 使用阴影来模拟其他两个按钮 */
}


  
}
</style>

![image](https://github.com/AirboZH/halo-theme-chirpy/assets/13695917/036a0117-2ad0-4e91-baed-5af58c03338e)
