### ISSUE TITLE
[BUG] 页面.container的内边距导致TopBar的背景颜色无法正常显示

### ISSUE THREAD

**Issue by Rlxzmdd** [AirboZH/halo-theme-chirpy#146]
【问题描述】：
. container具有一点内边距，导致topbar的颜色修改后留下两条边。

【截图】：
dom显示
![image](https://github.com/AirboZH/halo-theme-chirpy/assets/13695917/be823563-a303-4923-b8df-6abd3f2cb95e)
修改颜色后效果
![image](https://github.com/AirboZH/halo-theme-chirpy/assets/13695917/7071bad6-d4d7-4453-8be3-b947428cd136)

【网站链接】：
https://have.somuch.work/

**Comment by Rlxzmdd** [comment]
再看了下，发现tapbar是包含在container内的，且受限于container的宽度。
这样似乎无法单独为tapbar修改颜色。
我的想法是让tapbar颜色修改为：
![image](https://github.com/AirboZH/halo-theme-chirpy/assets/13695917/61bc97c3-4937-4c18-888a-d6a907ae83ab)
（灰色仅为表达区域）
希望能对此进行改进～

**Comment by AirboZH** [comment]
sorry，我不认为这是一个bug或者需要修改的地方，这应该属于一个比较个性化的需求。你可以fork本仓库并进行修改。

当然，目前我不会关闭这个Issue，如果有更多朋友支持这个Issue的话我会再考虑支持的。

**Comment by Rlxzmdd** [comment]
> sorry，我不认为这是一个bug或者需要修改的地方，这应该属于一个比较个性化的需求。你可以fork本仓库并进行修改。
> 
> 当然，目前我不会关闭这个Issue，如果有更多朋友支持这个Issue的话我会再考虑支持的。

好的

**Comment by waite0603** [comment]
> 再看了下，发现tapbar是包含在container内的，且受限于container的宽度。 这样似乎无法单独为tapbar修改颜色。 我的想法是让tapbar颜色修改为： ![image](https://private-user-images.githubusercontent.com/13695917/302023369-61bc97c3-4937-4c18-888a-d6a907ae83ab.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY5NzIxNzIsIm5iZiI6MTcwNjk3MTg3MiwicGF0aCI6Ii8xMzY5NTkxNy8zMDIwMjMzNjktNjFiYzk3YzMtNDkzNy00YzE4LTg4OGEtZDZhOTA3YWU4M2FiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjAzVDE0NTExMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdmNDFhYWJiNjYwMDNlZTQ3MGRkZTM3NTg2NDBmMWYxYTBlYTY5NTAyMDkwNjJmMDg4NzczNThkYzUzNjQ4ZDcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.CaT-5jAaPdkdc0aFbzojFALgFVOUN6MiaRGAdCC5hyE) （灰色仅为表达区域） 希望能对此进行改进～

你可以采用代码注释的方式实现你想要的效果, 如下:

```html
<style>
  #topbar-wrapper {
    margin-left: -3rem;
    margin-right: -3rem;
    background-color: your-color;
  }
</style>
```

如果你只是想修改背景颜色, 不想更改 `header` 中的显示效果
```html
<style>
  #topbar-wrapper {
    margin-left: -3rem;
    margin-right: -3rem;
    background-color: #888;
  }

  #topbar {
    margin-left: 3rem;
    margin-right: 3rem;
  }
</style>
```

最终效果如下:
![image](https://github.com/AirboZH/halo-theme-chirpy/assets/75354124/36d2ae25-e04b-495b-be07-2e3610f9c25f)

**Comment by Rlxzmdd** [comment]
> > 再看了下，发现tapbar是包含在container内的，且受限于container的宽度。 这样似乎无法单独为tapbar修改颜色。 我的想法是让tapbar颜色修改为： ![image](https://private-user-images.githubusercontent.com/13695917/302023369-61bc97c3-4937-4c18-888a-d6a907ae83ab.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY5NzIxNzIsIm5iZiI6MTcwNjk3MTg3MiwicGF0aCI6Ii8xMzY5NTkxNy8zMDIwMjMzNjktNjFiYzk3YzMtNDkzNy00YzE4LTg4OGEtZDZhOTA3YWU4M2FiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjAzVDE0NTExMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdmNDFhYWJiNjYwMDNlZTQ3MGRkZTM3NTg2NDBmMWYxYTBlYTY5NTAyMDkwNjJmMDg4NzczNThkYzUzNjQ4ZDcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.CaT-5jAaPdkdc0aFbzojFALgFVOUN6MiaRGAdCC5hyE) （灰色仅为表达区域） 希望能对此进行改进～
> 
> 你可以采用代码注释的方式实现你想要的效果, 如下:
> 
> ```
> <style>
>   #topbar-wrapper {
>     margin-left: -3rem;
>     margin-right: -3rem;
>     background-color: your-color;
>   }
> </style>
> ```
> 
> 如果你只是想修改背景颜色, 不想更改 `header` 中的显示效果
> 
> ```
> <style>
>   #topbar-wrapper {
>     margin-left: -3rem;
>     margin-right: -3rem;
>     background-color: #888;
>   }
> 
>   #topbar {
>     margin-left: 3rem;
>     margin-right: 3rem;
>   }
> </style>
> ```
> 
> 最终效果如下: ![image](https://private-user-images.githubusercontent.com/75354124/302043444-36d2ae25-e04b-495b-be07-2e3610f9c25f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY5NzQwNjksIm5iZiI6MTcwNjk3Mzc2OSwicGF0aCI6Ii83NTM1NDEyNC8zMDIwNDM0NDQtMzZkMmFlMjUtZTA0Yi00OTViLWJlMDctMmUzNjEwZjljMjVmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjAzVDE1MjI0OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY5MDJhOGViOGFlYTY2M2E1MmI0YmNlZTBmYmI4Yzk0YjYyODg5NDZhNDNjYzc5ZGE1YjFjMTNkN2I2ZGQxZDAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.mRu6-VTSBhPB_2U11MudHUsQqgQkQR74aSNrQFUg0xE)

牛的，没想到能这样写。太久没写前端了😂
