### ISSUE TITLE
升级1.4.1后前端文章详情中代码块错位

### ISSUE THREAD

**Issue by xxy-cn** [AirboZH/halo-theme-chirpy#152]
升级主题版本到1.4.1后，文章详情页中的代码块错位了，且代码中莫名显示1 2 3 4 这种数字，我用的编辑器是 ByteMD。
<img width="935" alt="image" src="https://github.com/AirboZH/halo-theme-chirpy/assets/58839118/18221149-db6b-48ae-935a-5b20b0624ce5">

**Comment by AirboZH** [comment]
你好，数字应该是行号。
你有网站域名吗？我看一下是什么原因导致的。

**Comment by xxy-cn** [comment]
> 你好，数字应该是行号。 你有网站域名吗？我看一下是什么原因导致的。

https://grizzly.pub/archives/oracle-sql-cha-xun-huo-qu-ren-yuan-zui-xin-yi-tiao-tong-xing-ji-lu

**Comment by xxy-cn** [comment]
> 应该是和PluginPrismJS插件冲突了

get了，感谢🙏
