### ISSUE TITLE
左侧的标签归档如何通过主题实现哈。

### ISSUE THREAD

**Issue by boommanpro** [AirboZH/halo-theme-chirpy#153]
hello，作者。左侧的标签归档如何通过主题实现哈。

**Comment by AirboZH** [comment]
猜你想问的是侧栏菜单如何修改
通过 conosle-菜单-主菜单 就可以修改了 
![image](https://github.com/AirboZH/halo-theme-chirpy/assets/50261327/c29f2edb-432e-479b-9cda-8702bda55b23)
