### ISSUE TITLE
页面的评论数据异常

### ISSUE THREAD

**Issue by ruibaby** [AirboZH/halo-theme-chirpy#156]
https://github.com/AirboZH/halo-theme-chirpy/blob/6db566ca7cbb429087ed1fe1ae2e71b2e173158a/templates/page.html#L22

这里应该是 SinglePage，参考：https://docs.halo.run/developer-guide/theme/template-tag

**Comment by AirboZH** [comment]
收到反馈 thanks@ruibaby
