### ISSUE TITLE
博主，请问下怎么更改首页文章全文显示

### ISSUE THREAD

**Issue by gamersky998** [AirboZH/halo-theme-chirpy#159]
用的分辨率较大，而且文章内容有点空，目前想首页文章全文显示
![image](https://github.com/AirboZH/halo-theme-chirpy/assets/48005973/629a2996-f414-49fc-9833-abdf29e62e0f)

**Comment by AirboZH** [comment]
文章内容有点空这个是因为在高分辨率的屏幕上统一设置成1200px左右的宽度，应该是比较普遍的做法。

> 首页文章全文显示

这个首页文章全文显示是什么意思呢？

**Comment by gamersky998** [comment]
就

> 文章内容有点空这个是因为在高分辨率的屏幕上统一设置成1200px左右的宽度，应该是比较普遍的做法。
> 
> > 首页文章全文显示
> 
> 这个首页文章全文显示是什么意思呢？

就是类似TYPECHO，或者WP那种老的默认主题，首页的文章列表显示方式不是摘要不是用200字数截取，而是全部显示出来

**Comment by AirboZH** [comment]
> 就是类似TYPECHO，或者WP那种老的默认主题，首页的文章列表显示方式不是摘要不是用200字数截取，而是全部显示出来

目前主题主页的文章是卡片的形式展示的，应该不太适合这么做。

**Comment by gamersky998** [comment]
> > 就是类似TYPECHO，或者WP那种老的默认主题，首页的文章列表显示方式不是摘要不是用200字数截取，而是全部显示出来
> 
> 目前主题主页的文章是卡片的形式展示的，应该不太适合这么做。

那如图那样的，左边的侧栏能否像右边的侧栏那样靠中间文章页对齐，一到分辨率，左边侧栏和中间文章页空一大堆白的，强迫症好难受

**Comment by AirboZH** [comment]
> 那如图那样的，左边的侧栏能否像右边的侧栏那样靠中间文章页对齐，一到分辨率，左边侧栏和中间文章页空一大堆白的，强迫症好难受

这个地方应该是考虑到内容和右边的侧栏一起居中的。这样看是不是就协调一点了。
如果还是不习惯，可以在`后台-设置-代码注入`自定义css样式

**Comment by AirboZH** [comment]
暂时关闭了，如果有其他问题可以继续讨论~
