### ISSUE TITLE
最新版本1.4.3，不支持加入页脚代码

### ISSUE THREAD

**Issue by amuguelove** [AirboZH/halo-theme-chirpy#162]
在Halo中添加了页脚的备案脚本后，但是在页面上不展示，切换到其他主题都可以展示备案信息

**Comment by amuguelove** [comment]
<img width="939" alt="image" src="https://github.com/AirboZH/halo-theme-chirpy/assets/9649106/c55a9c7a-8224-4262-967d-007b996b8738">

**Comment by amuguelove** [comment]
<img width="1324" alt="image" src="https://github.com/AirboZH/halo-theme-chirpy/assets/9649106/64fabd53-a5f2-4fb8-90c4-5a7d7271c0c7">

**Comment by AirboZH** [comment]
主题设置有一个开启站点信息，打开开关之后在右侧侧栏

**Comment by amuguelove** [comment]
It's ok, Thank you.
