### ISSUE TITLE
Version 1.4.3 无法展示Favicon

### ISSUE THREAD

**Issue by amuguelove** [AirboZH/halo-theme-chirpy#163]
现状：
已经在管理端配置好了favicon图片
<img width="593" alt="image" src="https://github.com/AirboZH/halo-theme-chirpy/assets/9649106/fe7690d2-0189-45bf-87c6-5493aea55aff">

问题：
<img width="266" alt="image" src="https://github.com/AirboZH/halo-theme-chirpy/assets/9649106/b658acf6-2132-4616-8031-2f870301bc56">
但是切换其他主题是可以展示的

**Comment by AirboZH** [comment]
可以提供一下 html 中这个icon的代码吗？这个似乎和主题没有关系，是halo系统决定的。
![image](https://github.com/AirboZH/halo-theme-chirpy/assets/50261327/c17c1806-14ec-4415-bc2a-adf25b540f3b)

**Comment by amuguelove** [comment]
> 可以提供一下 html 中这个icon的代码吗？这个似乎和主题没有关系，是halo系统决定的。 ![image](https://private-user-images.githubusercontent.com/50261327/316074310-c17c1806-14ec-4415-bc2a-adf25b540f3b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTExMjYyMzAsIm5iZiI6MTcxMTEyNTkzMCwicGF0aCI6Ii81MDI2MTMyNy8zMTYwNzQzMTAtYzE3YzE4MDYtMTRlYy00NDE1LWJjMmEtYWRmMjViNTQwZjNiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzIyVDE2NDUzMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTlkY2Y3NTViM2RiMDQ5NDRmOTU2ZTkzODY1NDhlY2VhZWU3ODE2OTBkMzhhYTQ1MTg4ZWEwMzg0NDQ2YWYyNTYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.RiEoYzXKl-lb0FiLLtMLltePi0auwRlQ964f1rc3_5w)

**Comment by amuguelove** [comment]
![image-20240323005311969](https://pic-bed-1256249917.cos.ap-chengdu.myqcloud.com/uPic/image-20240323005311969.png)

**Comment by AirboZH** [comment]
看起来一切正常， 我不认为这个问题和主题有关
我也无法解决这个问题。

**Comment by AirboZH** [comment]
https://github.com/AirboZH/halo-theme-chirpy/releases/tag/v1.4.4 新版本已发布
