### ISSUE TITLE
全局 head 标签 的代码，却配置到了html body中

### ISSUE THREAD

**Issue by amuguelove** [AirboZH/halo-theme-chirpy#164]
问题：
配置了全局的head，但是却放在body里面

<img width="720" alt="image" src="https://github.com/AirboZH/halo-theme-chirpy/assets/9649106/84878931-71b3-4146-bc31-1638c523e2e3">
<img width="996" alt="image" src="https://github.com/AirboZH/halo-theme-chirpy/assets/9649106/79cb55cb-45e6-4ec4-8c33-308b72695385">

**Comment by amuguelove** [comment]
切换了下其他主题，都是放在head里面

**Comment by AirboZH** [comment]
收到！
