### ISSUE TITLE
[建议] 增加博文图片点击放大功能的支持

### ISSUE THREAD

**Issue by mrfengye2021** [AirboZH/halo-theme-chirpy#165]
博文的图片点击无法放大，建议增加博文图片点击放大功能的支持！

**Comment by mrfengye2021** [comment]
MySQL语法不高亮，建议增加一个代码收缩功能
![QQ截图20240406000157](https://github.com/AirboZH/halo-theme-chirpy/assets/90916985/e896ab3d-1e0a-4ac7-83e6-af5755e1dd8e)

**Comment by mrfengye2021** [comment]
建议在网站信息哪里增加一个访客功能，还有网站运行时间，看自己需要选择开启
![QQ截图20240406000641](https://github.com/AirboZH/halo-theme-chirpy/assets/90916985/55ca76a8-2760-4df5-8f91-a4f01fa09b89)

**Comment by mrfengye2021** [comment]
建议增加一个文章字数显示功能
![QQ截图20240406001053](https://github.com/AirboZH/halo-theme-chirpy/assets/90916985/0a147c11-b8c7-48a4-ad25-99e891147476)

**Comment by AirboZH** [comment]
> MySQL语法不高亮，建议增加一个代码收缩功能

![image](https://github.com/AirboZH/halo-theme-chirpy/assets/50261327/4e8277b2-0caf-4bda-b806-66493d8732b8)

可以尝试
```
    ```SQL
    ```
```
SQL应该可以作为一个高亮语言。

代码块收缩会考虑的。

**Comment by AirboZH** [comment]
> 建议增加一个文章字数显示功能

鼠标放在阅读时间上会有一个悬浮的提示框，我认为阅读时间更直观，字数更详细，层级高一些逻辑也算合理。

**Comment by AirboZH** [comment]
> 建议在网站信息哪里增加一个访客功能，还有网站运行时间，看自己需要选择开启 

目前可以通过一些第三方服务自行增加，主题支持这个功能优先级不会特别高。

**Comment by AirboZH** [comment]
与 #158  #161 重复

**Comment by AirboZH** [comment]
@mrfengye2021 感谢你的支持和建议，如果有其他建议可以开启新的 issues，每个 issue 应该只处理一个问题

**Comment by AirboZH** [comment]
https://github.com/AirboZH/halo-theme-chirpy/releases/tag/v1.4.4 新版本支持了灯箱效果
