### ISSUE TITLE
文章目录过多不显示问题

### ISSUE THREAD

**Issue by mrfengye2021** [AirboZH/halo-theme-chirpy#171]
我的文章目录的标题有三十多个，就不显示了，在halo的编辑器可以显示，标题也可以跳转
![image](https://github.com/AirboZH/halo-theme-chirpy/assets/90916985/1e4fa649-d531-4801-ae76-ac7be64bb0db)

开始我全部采用的是二级标题但是，目录可以显示，但是点击无法跳转

后面全部改成三级标题进行尝试，全部该成三级标题之后就不显示了
![image](https://github.com/AirboZH/halo-theme-chirpy/assets/90916985/8625bb87-75bc-446e-983d-6beffe206712)

**Comment by AirboZH** [comment]
这个地方的思路是三级目录需要隐藏在二级目录之后，需要上级目录做折叠
![image](https://github.com/AirboZH/halo-theme-chirpy/assets/50261327/498f99e8-85ae-4d48-8235-ad717e51a7d2)
![image](https://github.com/AirboZH/halo-theme-chirpy/assets/50261327/4a08d1da-3709-451a-99a1-59d930ff76e5)

**Comment by AirboZH** [comment]
如有新进展再打开issue，暂时关闭
