### ISSUE TITLE
评论内容对比度太低。。看不清文字

### ISSUE THREAD

**Issue by anyanf** [AirboZH/halo-theme-chirpy#176]
<img width="264" alt="image" src="https://github.com/AirboZH/halo-theme-chirpy/assets/12234053/1af8130f-cd17-4fda-8c07-0aa19ebc6bfb">

如图。。

**Comment by AirboZH** [comment]
不应该哈，您是最近更新的主题吗？检查一下css缓存。还没有解决可以发我您的博客地址。

![Screenshot_2024-04-14-19-50-36-932_com.microsoft.emmx.jpg](https://github.com/AirboZH/halo-theme-chirpy/assets/50261327/1c7432f8-11fc-4878-ae94-da50d187d3ce)
