### ISSUE TITLE
友链模板下的页脚悬浮的版权提示tooltip位置有问题

### ISSUE THREAD

**Issue by Airsado** [AirboZH/halo-theme-chirpy#179]
在其他页面是正常的，只有在友链页面下，页脚版权协议悬浮的位置是不正常的。

**友链页面下：**

![image](https://github.com/user-attachments/assets/f8f79bac-2c40-4db1-951e-50acf2e93e0d)

**正常情况下：**

![image](https://github.com/user-attachments/assets/45269a62-5b5f-4009-895d-1695838d0195)

**Comment by AirboZH** [comment]
![image](https://github.com/user-attachments/assets/06079e7b-a4b3-4ed1-ab6b-41653e160db4)
![image](https://github.com/user-attachments/assets/b0b3310e-36ef-46f9-9de1-98855367bef6)

无法复现这个问题，可以提供一个线上的地址我看一下吗

**Comment by Airsado** [comment]
> ![image](https://private-user-images.githubusercontent.com/50261327/354479480-06079e7b-a4b3-4ed1-ab6b-41653e160db4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI1NzgwNTQsIm5iZiI6MTcyMjU3Nzc1NCwicGF0aCI6Ii81MDI2MTMyNy8zNTQ0Nzk0ODAtMDYwNzllN2ItYTRiMy00ZWQxLWFiNmItNDE2NTNlMTYwZGI0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODAyVDA1NDkxNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTgxNWE2YzRjZjA3NDlkYTY3MjBhMzE1ZDY1ZjgzM2VjN2E1MjE5OTJiYTY4ODAxNDdjZDljMzc0ZWIxYjJlZTMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.yP6UHvF-6wyXWdEoHBGM51E2hnj7_eHjeWykUjKvCJE) ![image](https://private-user-images.githubusercontent.com/50261327/354479575-b0b3310e-36ef-46f9-9de1-98855367bef6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI1NzgwNTQsIm5iZiI6MTcyMjU3Nzc1NCwicGF0aCI6Ii81MDI2MTMyNy8zNTQ0Nzk1NzUtYjBiMzMxMGUtMzZlZi00NmY5LTlkZTEtOTg4NTUzNjdiZWY2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODAyVDA1NDkxNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTk1Mjg0NWJmNzkwZTcxOTFlZDAwNDkxYzI2ZjNjYzEzNjMyMWUyM2VhZTEzODUxMmU4MDJlZTI1NzgzNTViMWEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.IDUvVsza0DspqVgPRp5NBqCdiGMqgtT2rTCksqaY5Ms)
> 
> 无法复现这个问题，可以提供一个线上的地址我看一下吗

我在查看readme的demo也发现有这个问题。同时我自己的博客也是存在这个问题。

使用了chrome以及edge浏览器也存在一样的问题

**demo网站：**

![image](https://github.com/user-attachments/assets/45d0933b-ceab-4324-9fff-1a01058a0d54)

**我自己的：**[这里](https://www.airsado.cn)
