### ISSUE TITLE
halo中主题一直提示更新至1.4.6

### ISSUE THREAD

**Issue by Airsado** [AirboZH/halo-theme-chirpy#186]
# 问题
halo 控制台更新主题一直提示更新

# 原因

`theme.yaml` 中的 `version`  仍然为 `1.4.4`

# 附件

![image](https://github.com/user-attachments/assets/9dbdd0b6-1a5f-4c25-a00d-94f8607361f4)

**Comment by AirboZH** [comment]
抱歉 忘了更新了。
马上处理一下
