### ISSUE TITLE
目录展示问题

### ISSUE THREAD

**Issue by DayBreak8** [AirboZH/halo-theme-chirpy#188]
Hello！使用这个主题后，在本地编写MarkDown文档后，复制到halo文章中，点击发布查看文章没有展示目录。这是不是一个Bug呢。使用Halo默认主题后可以正常展示目录。

**Comment by AirboZH** [comment]
@DayBreak8  hi, 该主题的目录是从 h2 开始显示的，h1 我理解是文章标题。你可以检查一下自己的内容标题是不是从 h2 开始的，如果有问题我再看看。

**Comment by DayBreak8** [comment]
那就如说从H3开始也是不可以的吗？只能是H2开头是吧？

**Comment by AirboZH** [comment]
是的～
