### ISSUE TITLE
文章的分享能否换成国内从常用站点？

### ISSUE THREAD

**Issue by wuhao0015** [AirboZH/halo-theme-chirpy#191]
![image](https://github.com/user-attachments/assets/cf7665af-7841-41bc-9cff-56ccf77db6d4)
hello
这个主题文章分享的几个连接能否换成国内常用的几个站点，比如微信、QQ、知乎、csdn等等。。

**Comment by AirboZH** [comment]
微信的话 我看国内的做法是 放一个二维码 然后微信扫码打开这个网页。所以不存在所谓分享到微信这样的功能。

**Comment by wuhao0015** [comment]
我的意思是主题默认的分享都是些不常用的国外站点，或者说这些站点在国内无法正常访问，在分享按钮上多点国内的分享站点。
我看官方默认主题的分享还行，但是又不会改呢。。
![image](https://github.com/user-attachments/assets/ef126963-7ced-4c01-a888-adf0f8283de0)

**Comment by AirboZH** [comment]
官方这个后续可能做成插件 等他们插件做出来用这个吧
