### ISSUE TITLE
新手求助

### ISSUE THREAD

**Issue by ch-davis** [AirboZH/halo-theme-chirpy#194]
您好
     是用您的主题以后怎么更改菜单的图标呢？按照您说的没搞定。。。。。。。。。

**Comment by AirboZH** [comment]
https://github.com/AirboZH/halo-theme-chirpy/wiki/%E4%B8%BB%E9%A2%98%E4%BD%BF%E7%94%A8%E6%96%87%E6%A1%A3
你是怎么操作的呢？

**Comment by ch-davis** [comment]
比方说 用 fa-light fa-house这个图标 在菜单中编辑元数据在key中填入 fa-light fa-house ，保存后在页面中刷新并没改变，还是默认的
![屏幕截图 2024-12-29 204624](https://github.com/user-attachments/assets/6fff033e-faca-41a7-8271-06e89067f95b)

这是主题默认的样子
![屏幕截图 2024-12-29 204657](https://github.com/user-attachments/assets/81b92332-6791-4a32-b8be-ff7948227e5d)

**Comment by ch-davis** [comment]
> https://github.com/AirboZH/halo-theme-chirpy/wiki/%E4%B8%BB%E9%A2%98%E4%BD%BF%E7%94%A8%E6%96%87%E6%A1%A3 你是怎么操作的呢？
比方说用 fa-light fa-house这个图标 
![屏幕截图 2024-12-29 204624](https://github.com/user-attachments/assets/7edb5406-636a-41ee-b709-1c6fce28d24b)
填入后并没有变化 还是默认的图标
![屏幕截图 2024-12-29 204657](https://github.com/user-attachments/assets/7cc2332a-8a06-44e7-a866-ad66cec4ad8b)

**Comment by AirboZH** [comment]
<img width="292" alt="image" src="https://github.com/user-attachments/assets/80ef7a89-5965-49ed-b3ec-17b69963a647" />

key 是icon value 是fa-light fa-house

**Comment by ch-davis** [comment]
> <img alt="image" width="292" src="https://private-user-images.githubusercontent.com/50261327/399161288-80ef7a89-5965-49ed-b3ec-17b69963a647.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzU0NzcyMDEsIm5iZiI6MTczNTQ3NjkwMSwicGF0aCI6Ii81MDI2MTMyNy8zOTkxNjEyODgtODBlZjdhODktNTk2NS00OWVkLWIzZWMtMTdiNjk5NjNhNjQ3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjI5VDEyNTUwMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWY3MjI3N2EzMmU3ZWRhY2I5Yjg1NGEyNTYxMGYyOTJjYTVmM2U2YzE5YTY4Mjg3MzcxZDljZjYzZTAzNDIwNTgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.5RC8OPuWcpR3YlA3il_PYtmGxiR9hqvdHm0SPEQy8bc">
> key 是icon value 是fa-light fa-house

感谢，感谢大神
