### ISSUE TITLE
右侧 Trending Tags 中标签跳转链接不对

### ISSUE THREAD

**Issue by wan92hen** [AirboZH/halo-theme-chirpy#3]
目前跳转链接为 `/tag/标签名`，应该是 `/tags/标签名`。
![image](https://github.com/AirboZH/halo-theme-chirpy/assets/27671436/d3a7c713-42e9-4de4-a59b-bd53117b113b)

**Comment by AirboZH** [comment]
> 目前跳转链接为 `/tag/标签名`，应该是 `/tags/标签名`。
> ![image](https://github.com/AirboZH/halo-theme-chirpy/assets/27671436/d3a7c713-42e9-4de4-a59b-bd53117b113b)
> 
> 

好的，谢谢，很快就会处理

**Comment by AirboZH** [comment]
thanks for your bug reports, let @all-contributors add @wan92hen for bug
