### ISSUE TITLE
文章摘要不显示

### ISSUE THREAD

**Issue by Jamtoal** [AirboZH/halo-theme-chirpy#4]
如题，在console端已设置文章自动生成摘要，但是首页列出的文章只包括标题，摘要不显示

**Comment by AirboZH** [comment]
感谢反馈，我看一下什么愿意造成的

**Comment by AirboZH** [comment]
@Jamtoal thans for report bugs cc. @all-contributors

**Comment by AirboZH** [comment]
@all-contributors please add @Jamtoal  for bug
