### ISSUE TITLE
适配暗色模式下搜索插件颜色

### ISSUE THREAD

**Issue by NovaShen555** [AirboZH/halo-theme-chirpy#46]
halo version: 2.8.0
theme version: 1.0.4

在黑暗模式下点击搜索框屏幕表现仍与亮色模式相
希望改进：白色的半透明改为黑色的半透明，搜索框底色改为黑

**Comment by AirboZH** [comment]
这个搜索框都颜色是搜索插件决定的，可能没那么好改🙁之前和halo开发者聊过，搜索插件可能会重构 到时候或许有比较好的解决方案🤔

不过还是谢谢你的想法❤️，我明天看一看目前有没有临时的实现方法～😎

**Comment by AirboZH** [comment]
thanks for your idea, @all-contributors will add @NovaShen555 for ideas

**Comment by NovaShen555** [comment]
所以此issue有希望做了吗

**Comment by AirboZH** [comment]
这周忙忘了，您稍等我现在看看

**Comment by AirboZH** [comment]
目前有一个比较低效的办法，明天试一下

**Comment by AirboZH** [comment]
@NovaShen555 我试了一下感觉成本实在是太高了，要变动的地方很多，而且颜色也不好看。

![image](https://github.com/AirboZH/halo-theme-chirpy/assets/50261327/923c41e2-e957-4ffd-a876-7311028c0a29)

你可以在插件下面提IS试试看，https://github.com/halo-sigs/plugin-search-widget/issues

**Comment by AirboZH** [comment]
Halo应该会提供相关接口了，可能需要等一段时间。到时候我去适配。
https://github.com/halo-sigs/plugin-comment-widget/issues/56#issuecomment-1720366672

**Comment by NovaShen555** [comment]
好的感谢！
