### ISSUE TITLE
适配评论插件

### ISSUE THREAD

**Issue by CheneyWong** [AirboZH/halo-theme-chirpy#56]
后台设置中的评论设置是打开的，文章的评论也是打开的。
开启其他主题，有评论框。
开始 chirpy 主题没有评论框。

http://gpio.me/

**Comment by AirboZH** [comment]
@CheneyWong 感谢您喜欢 [halo-theme-chirpy](https://github.com/AirboZH/halo-theme-chirpy)😊

目前主题还没有适配评论插件，我将尽快适配🫡 
预计三天内完成适配。到时候这条Issues下会有消息提醒。

**Comment by AirboZH** [comment]
@CheneyWong 当前问题已经合并代码但还没有发布 如果您想体验的话可以在 https://github.com/AirboZH/halo-theme-chirpy/actions/runs/6120040806 这里下载主题包

**Comment by CheneyWong** [comment]
评论功能已验证可用。
在夜间模式显示良好。在日间模式，字的颜色还是白色，优点看不清。

**Comment by AirboZH** [comment]
> 评论功能已验证可用。 在夜间模式显示良好。在日间模式，字的颜色还是白色，优点看不清。

目前可能需要换完颜色刷新一下

我是写了模式兼容的代码的，但是有些情况不生效，我再看看吧。

**Comment by AirboZH** [comment]
重新打开我再优化优化

**Comment by AirboZH** [comment]
thanks for your idea, @all-contributors will add @CheneyWong for ideas

**Comment by AirboZH** [comment]
经过排查，您反馈的
> 在日间模式，字的颜色还是白色，有点看不清。  

这个问题应该已经解决了，但是js文件缓存更新不及时。
问题会在今天发布的v1.0.6中得到解决。升级版本即可~

**Comment by AirboZH** [comment]
fix bug in https://github.com/AirboZH/halo-theme-chirpy/commit/5dc063cb1683d8a62cbf4edec128eea8fc3b947e
