### ISSUE TITLE
主题js和css加载失败

### ISSUE THREAD

**Issue by Jamtoal** [AirboZH/halo-theme-chirpy#7]
halo升级到2.8之后，主题的js和css加载失败，使用vpn才能成功加载资源
![d1d199416ddcf029e4c6bad3ca9c93c](https://github.com/AirboZH/halo-theme-chirpy/assets/91370415/0d4e10c2-6e68-49be-a85f-55e8d3c29ab9)

**Comment by AirboZH** [comment]
jsdelivr在国内可能不是很稳定，我回头换一个cdn或者将这些文件重新分发一下
![image](https://github.com/AirboZH/halo-theme-chirpy/assets/50261327/fcded3c4-1415-4bf8-94c6-b343d4ddd7ef)

**Comment by ruibaby** [comment]
我建议依赖直接管理在项目内，不使用三方的 CDN。

**Comment by AirboZH** [comment]
> 我建议依赖直接管理在项目内，不使用三方的 CDN。  

@ruibaby   
好的👌 也方便主题管理，目前[Bootstrap](https://github.com/twbs/bootstrap) 和 [Font Awesome Free](https://fontawesome.com/) 就是这么做的，后续将其他依赖也集成到项目中
