### ISSUE TITLE
Markdown 代码样式想法

### ISSUE THREAD

**Issue by SinclairLin** [AirboZH/halo-theme-chirpy#78]
提一个小小的想法，`Markdown`语法在使用反引号`` ` ``对行内代码进行标记时，显示的是这样的效果：

> ![img1](https://img.sinclairl.com/file/images-sinclair/2023/2a9117d8b9622a82018b29559bcb7ffe.png "这是没加空格的")

私以为，这个样式会对文章的可读性造成一定的影响，这导致我在用这个主题撰写文章的时候，需要额外的多在两个反引号`` ` `` 的左右两边各插入一个空格，以提升可读性：

> ![img2](https://img.sinclairl.com/file/images-sinclair/2023/6ccc5833d522e73851e6e8012188fbc2.png "这是加了空格的")

并且就算加了空格，代码周围的空白也会让我看着有点别扭。

> 因为需要用反引号进行标注的一般都是英文单词，在不使用等宽字体的情况下，英文字母`i`与`m`的宽度不一，所造成的单词与汉字之间的间隔(肉眼看起来)不一致，容易造成观感割裂。
> 
> ![image-20230913010036503](https://img.sinclairl.com/file/images-sinclair/2023/831e11a248cee6eaf9516a128203fa55.png)

- **改进意见**：类似`Github`这样的行内代码显示效果我个人认为就挺不错的，即在被标记的文本后面加背景：

    > ![img3](https://img.sinclairl.com/file/images-sinclair/2023/04e95d7ecad00ba816366a6902f3c71c.png "这是 Github 的显示方案")

*当然以上谨代表我个人想法，如果你有什么其他的想法或是觉得这个`issue`不妥，请指教或者直接`close`它，谢谢！*

**Comment by AirboZH** [comment]
首先谢谢你的建议，我欢迎各种友善的交流，你真是太客气了。😊

在原主题中，他的效果和你说的是差不多的
![image](https://github.com/AirboZH/halo-theme-chirpy/assets/50261327/e636c014-b56f-4e5d-8860-0d80a06039a5)
但是在移植过来的过程中可能html和css不能有很好的匹配所以导致了这个问题🤔

我目前的方向是经可能还原主题，应该很快就可以适配了

这确实是我忽略的一个地方，再次感谢🫡

**Comment by AirboZH** [comment]
@SinclairLin  看一下这样的效果可以么
https://airbozh.tech/archives/post-test

**Comment by SinclairLin** [comment]
@AirboZH 可以的，我想要的正是这种效果。

**Comment by AirboZH** [comment]
> @AirboZH 可以的，我想要的正是这种效果。

好的，稍后我会提交这次更新并在后续版本中发布。🎉

**Comment by AirboZH** [comment]
@all-contributors please add @SinclairLin for ideas
