### ISSUE TITLE
不支持评论组件嘛

### ISSUE THREAD

**Issue by myannnascar** [AirboZH/halo-theme-chirpy#79]
好似不显示评论

**Comment by AirboZH** [comment]
@NovaShen555 还有点问题，我已经排查到了。
问题存在于系统配置是暗色主题的情况下，你提一个Issue吧

**Comment by NovaShen555** [comment]
> @NovaShen555 还有点问题，我已经排查到了。 问题存在于系统配置是暗色主题的情况下，你提一个Issue吧


已提
