### ISSUE TITLE
侧栏 FontAwesome X-Twitter 图标不显示

### ISSUE THREAD

**Issue by ccxxvv77** [AirboZH/halo-theme-chirpy#8]
如题
Halo 2.8.0由1Panel部署
Chirpy 1.0.1 深色模式
侧栏 `fab fa-x-twitter` 与 `fab fa-square-x-twitter` 均不显示

**Comment by AirboZH** [comment]
这个图标使用的版本是6.4.2，本项目图标使用的是[fontawesome-free@6.4.0_css_all.min.css](https://github.com/AirboZH/halo-theme-chirpy/blob/master/templates/assets/lib/fontawesome-free%406.4.0_css_all.min.css)
等进行版本更新后就可以显示了，感谢反馈~

**Comment by AirboZH** [comment]
我会在这个issue下处理这个问题，到时候应该会收到邮件提醒，请稍等几日

**Comment by ccxxvv77** [comment]
OK解决了
不过我也不用halo了😥
Anyway, appreciation for the epic work

**Comment by AirboZH** [comment]
先打开吧，我后面也会更新依赖的。😊

**Comment by AirboZH** [comment]
@all-contributors please add @ccxxvv77  for bug
