### ISSUE TITLE
归档页面文字未对齐

### ISSUE THREAD

**Issue by NovaShen555** [AirboZH/halo-theme-chirpy#85]
归档页面中日期显示以DD/MM方式进行
DD为一位数时和两位数时会有一个字符的缩进未处理
![image](https://github.com/AirboZH/halo-theme-chirpy/assets/122534619/6dbcec58-4365-4c48-ba4f-020932f3b687)
俩图一样，那个加载快就看哪个
![image2](https://cdn.staticaly.com/gh/NovaShen555/picx-images-hosting@master/20230916/1694796340816.jpg)

   

然后呢我的初步想法是DD为一位数时在前方添加前导0，如图
![image3](https://cdn.staticaly.com/gh/NovaShen555/picx-images-hosting@master/20230916/1694796453927.jpg)
  
   
或者是在数字前方进行缩进以对齐两位数的第二位数字
检查中弄不出来，不清楚能不能做
😂😂
辛苦啦

**Comment by AirboZH** [comment]
![Screenshot_2023-09-16-06-12-21-189_com.microsoft.emmx.jpg](https://github.com/AirboZH/halo-theme-chirpy/assets/50261327/d45e93a7-a81c-4423-887f-75cef3543f60)

你说的样子是像这样吗?后面两个图我看不到可能文件有点问题。
没问题这个可以做，确实是我主题的一个bug

感谢反馈

事实上你就尽管提出要求就行，不用管技术上如何实现，要做到体验完美就应该全力以赴追求细节～

**Comment by NovaShen555** [comment]
是的，这样的效果是不错的，或者是在DD的数字前方进行缩进以对齐两位数的第二位数字
您能理解我的意思吧
