### ISSUE TITLE
[bug] 评论组件黑色模式下仍显示为白色

### ISSUE THREAD

**Issue by NovaShen555** [AirboZH/halo-theme-chirpy#94]
![269678525-515a556c-e5a0-4138-9920-30b4242d959c](https://github.com/AirboZH/halo-theme-chirpy/assets/122534619/e07ddac6-18c7-4233-9d0a-16470cf97fd8)
rt

**Comment by AirboZH** [comment]
@all-contributors please add @NovaShen555  for bug
