### ISSUE TITLE
自定义页面评论组件适配问题

### ISSUE THREAD

**Issue by waite0603** [AirboZH/halo-theme-chirpy#96]
![image](https://github.com/AirboZH/halo-theme-chirpy/assets/75354124/9d33b4b7-92e5-474f-9efd-ac51ca280fbe)

**Comment by AirboZH** [comment]
#94

**Comment by AirboZH** [comment]
抱歉，最近有些忙，这个问题已经解决~  详见：https://github.com/AirboZH/halo-theme-chirpy/pull/105
目前 1.2.0 版本尚未发布
您可以通过 https://github.com/AirboZH/halo-theme-chirpy/actions/runs/6490103594 下方的Artifacts下载更新使用
