### ISSUE TITLE
强烈建议支持以Github的Markdown样式展示文章正文

### ISSUE THREAD

**Issue by muyangren918** [AirboZH/halo-theme-chirpy#99]
目前正在使用halo-theme-chirpy主题，全部文章都是使用markdown编写的，个人感觉markdown样式做的最好的就是Github。VSCode中的markdown插件有提供Github Markdown样式，以前免费现在付费的Typora也支持Github样式的主题。Github的markdown样式呈现效果是结构清晰，美观又大方。强烈建议halo-theme-chirpy主题支持以Github的markdown样式展示文章正文。目前的halo-theme-chirpy主题展示文章中的代码段时的表现一言难尽。

**Comment by AirboZH** [comment]
我没太明白您说的markdown样式到底是什么，是一级~六级标题，字体斜体，引用这些样式么。
作为[jekyll-theme-chirpy](https://github.com/cotes2020/jekyll-theme-chirpy)移植主题，应该是没有计划支持上面的样式。

您说的第二个代码块的问题，我们在[其他Issue](https://github.com/AirboZH/halo-theme-chirpy/issues/28)中已有相应计划，下一阶段计划就是适配代码块。目前您可以通过安装高亮插件来缓解这个问题。

**Comment by muyangren918** [comment]
感谢，目前正在采用您提到的代码高亮插件。
至于我说的Github主题，指的是希望文章内容展示页面可以选择采用Github的Markdown样式，比如你们代码仓库首页的MD文档就是以Github的Markdown样式展示的。
下图1是Typora，默认以Github的Markdown样式展示MD文档。
下图2是VSCode中我正在使用的MD预览插件提供的一种可选样式。
下图3是图片2中的样式插件的实际展示效果。
个人猜测，Typora也好，VSCode中的MD预览插件也好，他们都是把Github官方的MD文档展示样式复制了过去，不知道Github官方是否有专门的网站公开这些样式，他们总不至于扒Github的CSS样式吧。
包括上面提到的Typora和VSCode的MD预览插件在内，我书写MD和查看MD喜欢并习惯使用Github主题，因为我觉得该主题阅读体验非常好，层次感对比度恰到好处。所以提Issue的目的就是想知道文章展示页面有没有提供可选样式的Plan，类似于Typora和VSCode的MD预览插件那样。
![image](https://github.com/AirboZH/halo-theme-chirpy/assets/65386952/5959db41-da93-4fee-8626-70477ba2d220)
![image](https://github.com/AirboZH/halo-theme-chirpy/assets/65386952/587543dc-cf7d-43f7-95e1-ee6ea8478fad)
![image](https://github.com/AirboZH/halo-theme-chirpy/assets/65386952/e7fd2743-486b-47ba-90e7-4f91e404493b)

**Comment by AirboZH** [comment]
代码块中可能会采用Github样式 #28

**Comment by AirboZH** [comment]
代码块目前采用了Github样式风格。
标题，列表等其他样式目前暂无改为 github 样式的想法
